/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TcExampleTitle {
        "text": string;
    }
}
declare global {
    interface HTMLTcExampleTitleElement extends Components.TcExampleTitle, HTMLStencilElement {
    }
    var HTMLTcExampleTitleElement: {
        prototype: HTMLTcExampleTitleElement;
        new (): HTMLTcExampleTitleElement;
    };
    interface HTMLElementTagNameMap {
        "tc-example-title": HTMLTcExampleTitleElement;
    }
}
declare namespace LocalJSX {
    interface TcExampleTitle {
        "text"?: string;
    }
    interface IntrinsicElements {
        "tc-example-title": TcExampleTitle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tc-example-title": LocalJSX.TcExampleTitle & JSXBase.HTMLAttributes<HTMLTcExampleTitleElement>;
        }
    }
}
